name: janus
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.10.5=h4c7d964_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - expat=2.7.1=h8ddb27b_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - libblas=3.9.0=38_hf2e6a31_mkl
  - libcblas=3.9.0=38_h2a3cdd5_mkl
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - liblapack=3.9.0=38_hf9ab0e9_mkl
  - libsqlite=3.51.0=hf5d6505_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.5=hfa2b4ca_0
  - llvmlite=0.45.1=py312hdb9728c_0
  - mkl=2025.3.0=hac47afa_454
  - numba=0.62.1=py312h9a042f1_0
  - openssl=3.5.4=h725018a_0
  - pip=25.2=pyhc872135_0
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - python=3.12.7=hce54a09_0_cpython
  - python_abi=3.12=8_cp312
  - scikit-learn=1.7.2=py312h91ac024_0
  - setuptools=80.9.0=py312haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tbb=2022.3.0=hd094cb3_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hf199647_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - ucrt=10.0.22621.0=haa95532_0
  - umap-learn=0.5.9.post2=py312h2e8e312_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - accelerate==1.10.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - diffusers==0.31.0
      - filelock==3.13.1
      - fonttools==4.60.1
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - huggingface-hub==0.26.2
      - idna==3.10
      - importlib-metadata==8.7.0
      - jinja2==3.1.4
      - kiwisolver==1.4.9
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==2.2.6
      - nvidia-ml-py==13.580.82
      - nvitop==1.5.3
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.0.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.9.18
      - requests==2.32.5
      - safetensors==0.6.2
      - scipy==1.16.2
      - seaborn==0.13.2
      - six==1.17.0
      - sympy==1.13.1
      - tokenizers==0.20.1
      - torch==2.5.0+cu124
      - torchaudio==2.5.0+cu124
      - torchvision==0.20.0+cu124
      - transformers==4.46.1
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - windows-curses==2.4.1
      - zipp==3.23.0